### ISSUE TITLE
API for checking whether the flashlight is on or not

### ISSUE THREAD

**Issue by Kisty** [nisrulz/lantern#2]
Would be great to have an API to get the state of the flashlight. Doing it at the source would have the most reliable state. At present, I'm settling for a `boolean` to keep track of the flashlight.

**Comment by nisrulz** [comment]
@Kisty Could you provide me a case where this would be helpful?

**Comment by Kisty** [comment]
Say if the user has turned on the flashlight by the notification drawer or another app. We'd need to know if the flashlight was on or off. Also, means that we wouldn't have to maintain a boolean in the app to keep track of when it is switched on or not

**Comment by nisrulz** [comment]
The internal flag makes sure that the flashlight is off before it will attempt to switch it on. In your use case, this still holds true. The fact is the user doesnot need to know about if it is on or not. When being triggered by the lib api, it is handled internally.

**Comment by Kisty** [comment]
Ah right. OK, but what happens if the flashlight is on and you have a button showing whether it's on or off. How else would you know if coming back to the app and the flashlight is on from another app or system drawer it's on?

**Comment by Kisty** [comment]
A bonus enhancement would be to check the torch status at the point of initialising Lantern and when listening for `onActivityStart`/`onActivityStop` (like the lifecycle integration 👍).

Consider the scenario:

1. User switches on torch from system menu
2. User comes in to our app
3. Lantern thinks it's off, so app shows as off (but device shows as on) <-- UX issue
4. Click button in app to switch lantern on.
5. Torch already on, does nothing, hmmm.

**Comment by nisrulz** [comment]
Yes, that is a valid use case. Feel free to open a PR when you get time, or else I will take it up this weekend.

Thank you :)

**Comment by nisrulz** [comment]
Closing as merged.
